name: C/C++ CI

on:
  push:
    branches: [ "Vladimir" ]
  pull_request:
    branches: [ "Vladimir" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: start_cmake
      run: cmake .
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
